// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auction/auction.proto

package auction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Auction service

func NewAuctionEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Auction service

type AuctionService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Auction_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Auction_PingPongService, error)
}

type auctionService struct {
	c    client.Client
	name string
}

func NewAuctionService(name string, c client.Client) AuctionService {
	return &auctionService{
		c:    c,
		name: name,
	}
}

func (c *auctionService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auction.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Auction_StreamService, error) {
	req := c.c.NewRequest(c.name, "Auction.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &auctionServiceStream{stream}, nil
}

type Auction_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type auctionServiceStream struct {
	stream client.Stream
}

func (x *auctionServiceStream) Close() error {
	return x.stream.Close()
}

func (x *auctionServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *auctionServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *auctionServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *auctionServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *auctionService) PingPong(ctx context.Context, opts ...client.CallOption) (Auction_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Auction.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &auctionServicePingPong{stream}, nil
}

type Auction_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type auctionServicePingPong struct {
	stream client.Stream
}

func (x *auctionServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *auctionServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *auctionServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *auctionServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *auctionServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *auctionServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Auction service

type AuctionHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Auction_StreamStream) error
	PingPong(context.Context, Auction_PingPongStream) error
}

func RegisterAuctionHandler(s server.Server, hdlr AuctionHandler, opts ...server.HandlerOption) error {
	type auction interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Auction struct {
		auction
	}
	h := &auctionHandler{hdlr}
	return s.Handle(s.NewHandler(&Auction{h}, opts...))
}

type auctionHandler struct {
	AuctionHandler
}

func (h *auctionHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AuctionHandler.Call(ctx, in, out)
}

func (h *auctionHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuctionHandler.Stream(ctx, m, &auctionStreamStream{stream})
}

type Auction_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type auctionStreamStream struct {
	stream server.Stream
}

func (x *auctionStreamStream) Close() error {
	return x.stream.Close()
}

func (x *auctionStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *auctionStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *auctionStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *auctionStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *auctionHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuctionHandler.PingPong(ctx, &auctionPingPongStream{stream})
}

type Auction_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type auctionPingPongStream struct {
	stream server.Stream
}

func (x *auctionPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *auctionPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *auctionPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *auctionPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *auctionPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *auctionPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
